import { v4 as uuidv4 } from 'uuid'
// eslint-disable-next-line no-unused-vars
import ColumnType from '@/constants/ColumnType'

export default () => ({
  /**
   * @type {String}
   * unique identifier of the column generated by the uuid module
   */
  uid: uuidv4(),
  /**
   * @type {String}
   * display name of the column, that is displayed in the editor
   */
  displayName: 'Column',
  /**
   * @type {String}
   * name of the column, used as a key in document object
   */
  name: 'Column',
  /**
   * @type {ColumnType}
   * type of the column
   */
  type: null,
  /**
   * @type {Number}
   * width of the column
   */
  width: 50,
  /**
   * @type {Array}
   * array of possible values (enum type only)
   */
  values: [],
  /**
   * @type {Boolean}
   * if multiple values can be selected (enum type only)
   */
  multiple: []
})
