import { v4 as uuidv4 } from 'uuid'

export default () => ({
  /**
   * @type {String}
   * unique identifier of the folder generated by the uuid module
   */
  uid: uuidv4(),
  /**
   * @type {String}
   * name of the folder
   */
  name: null,
  /**
   * @type {String}
   * unique identifier of the the parent folder/project that this folder belongs to
   */
  parentId: null
})
