import { v4 as uuidv4 } from 'uuid'

export default () => ({
  /**
   * @type {String}
   * unique identifier of the object generated by the uuid module
   */
  uid: uuidv4(),
  /**
   * @type {Number}
   * object id in the document, starts from 0
   */
  id: 0,
  /**
   * @type {String}
   * unique identifier of the document that this object belongs to
   */
  documentId: null,
  /**
   * @type {String}
   * type of the object, possible values are in ObjectType enum
   */
  type: 'PROSE',
  /**
   * @type {String}
   * text of this object
   */
  text: 'Default object text',
  /**
   * @type {String}
   * classification of the object, possible values are in ObjectClassification enum
   */
  classification: [],
  /**
   * @type {Boolean}
   * specifies if object is header (true) or just a paragraph (false)
   */
  isHeading: false,
  /**
   * @type {String}
   * if object is heading, this field is updated to reflect its chapter
   */
  chapter: '',
  /**
   * @type {String}
   * unique identifier of the the parent object that this object belongs to
   */
  parentId: null,
  /**
   * @type {Boolean}
   * Specifies if the object is the root object of the document. This object is not displayed and is only used as a parent, that objects are put under.
   */
  root: false,
  /**
   * @type {Array}
   * list of children objects of this object
   */
  objects: []
})
