import { v4 as uuidv4 } from 'uuid'

export default () => ({
  /**
   * @type {String}
   * unique identifier of the project generated by the uuid module
   */
  uid: uuidv4(),
  /**
   * @type {String}
   * name of the project
   */
  name: 'Project'
})
